title = "Home"
baseURL = "https://mysticazhang.github.io"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
#themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  tags = "/content/tags"
  favicon = ""
  description = ""
  facebook = "https://www.facebook.com/xiaoyu.zhang.9081"
  #twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = "https://www.linkedin.com/in/%E6%99%93%E9%9B%A8-%E5%BC%A0-0a7621101/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-white"
  featured_image = "/images/d.jpg"
  recent_posts_number = 2
